# Generated by Django 6.0.1 on 2026-01-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_created_at_service_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicevariant',
            options={'verbose_name': 'Service Variant', 'verbose_name_plural': 'Service Variants'},
        ),
        migrations.AlterUniqueTogether(
            name='servicevariant',
            unique_together={('service', 'name')},
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='servicevariant',
            table='service_variants',
        ),
    ]
