# Generated by Django 6.0.1 on 2026-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_options_alter_servicevariant_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicevariant',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='service_variant_gte=0'),
        ),
    ]
